package ae.skydoppler.skyblock_locations;

public enum SkyblockIslandType {
    NONE, HUB, PRIVATE_ISLAND, MINING_ISLAND, FARMING_ISLAND, FORAGING_ISLAND, FISHING_ISLAND, COMBAT_ISLAND, DUNGEON_ISLAND, KUUDRA_ISLAND, RIFT_ISLAND
}
