package ae.skydoppler.skyblock.skyblock_locations;

public enum SkyblockIslandCategoryEnum {
    NONE, HUB_ISLAND, PRIVATE_ISLAND, MINING_ISLAND, FARMING_ISLAND, FORAGING_ISLAND, FISHING_ISLAND, COMBAT_ISLAND, DUNGEON_ISLAND, KUUDRA_ISLAND, RIFT_ISLAND, SPECIAL_ISLAND
}
